# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

use_frameworks!

target 'Flash Chat iOS13' do

      
    pod 'Firebase/Core'
    pod 'Firebase/Auth'
    pod 'Firebase/Firestore'

end
