# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

use_frameworks!

target 'Flash Chat iOS13' do

      
    pod 'Firebase/Core' , '~> 5.0'
    pod 'Firebase/Auth' , '~> 5.0'
    pod 'Firebase/Firestore' , '~> 5.0'
    pod 'SKActivityIndicatorView', '~> 1.0.0'

end
