# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

use_frameworks!

target 'FirebasePushNotification' do
      
      pod 'SwiftyJSON', '~> 4.0'
      pod 'Firebase/Analytics' , '~> 5.0'
      pod 'Firebase/Messaging' , '~> 5.0'

end
